# Generated by Django 5.2 on 2025-04-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_rating_unique_together_remove_rating_recipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='recipes',
            field=models.ManyToManyField(blank=True, related_name='collections', to='main_app.recipe'),
        ),
    ]
