# Generated by Django 5.2 on 2025-05-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='photo_credit',
            field=models.CharField(blank=True, help_text='Optional: Credit the source or owner of the photo', max_length=255),
        ),
    ]
