# Generated by Django 5.2 on 2025-05-02 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_recipe_photo_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='cover_recipe',
            field=models.ForeignKey(blank=True, help_text='Recipe used as cover image for this collection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for_collections', to='main_app.recipe'),
        ),
    ]
