# Generated by Django 5.2 on 2025-05-04 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_collection_cover_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='source',
            field=models.URLField(blank=True, help_text='must be a valid URL', null=True),
        ),
    ]
