# Generated by Django 5.2 on 2025-05-05 01:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_recipe_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='photo_credit',
            field=models.CharField(blank=True, help_text='Credit the source or owner of the photo', max_length=255),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='source',
            field=models.URLField(blank=True, help_text='Must be a valid URL', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('name', 'user')},
        ),
    ]
