# Generated by Django 5.2 on 2025-05-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_recipe_photo_credit_alter_recipe_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='total_time',
            field=models.CharField(blank=True, help_text='time to prepare...', max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='yield_amount',
            field=models.CharField(blank=True, help_text='num of servings...', max_length=100),
        ),
    ]
